name: Build and deploy Jekyll site
on: [push]

jobs:
  jekyll:
    name: Build and deploy Jekyll site
    runs-on: ubuntu-latest
    environment: main

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Build
      uses: jerryjvl/jekyll-build-action@v1

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1

    - name: Auxiliary actions
      run: |
        git clone https://github.com/lenis2000/CV.git ./_site/research/CV
        mv ./_site/research/CV/__petrovCV__.pdf ./_site/research/petrovCV.pdf
        mv ./_site/research/CV/__petrovCV__short.pdf ./_site/research/petrovCVbrief.pdf
        rm -Rf _site/research/CV

        # get fresh githubbed syllabi from GitHub
        git clone https://github.com/lenis2000/Syllabi.git ./_site/teaching/syll
        mv ./_site/teaching/syll/Syllabus_2310_f16.pdf ./_site/teaching/
        mv ./_site/teaching/syll/Syllabus_3100_s17.pdf ./_site/teaching/
        mv ./_site/teaching/syll/Syllabus_3100_f18.pdf ./_site/teaching/
        mv ./_site/teaching/syll/Syllabus_7310_s19.pdf ./_site/teaching/
        mv ./_site/teaching/syll/Syllabus_7310_s20.pdf ./_site/teaching/
        mv ./_site/teaching/syll/Syllabus_3340_s20.pdf ./_site/teaching/
        mv ./_site/teaching/syll/Syllabus_3100_f20.pdf ./_site/teaching/
        rm -Rf _site/teaching/syll

    - name: Check HTML
      uses: chabad360/htmlproofer@master
      with:
        # The directory to scan
        directory: "./_site"
        # The arguments to pass to HTMLProofer
        arguments: --disable-external
          
    - name: Sync output to S3
      run: |
        aws s3 sync ./_site/ s3://lpetrov.cc --delete
